### PR TITLE
Force foreground color when setting background color

### LINKED ISSUE #116: Dark theme
Addon is unreadable when enabling dark theme.

How to reproduce : choose Customize > Themes > Compact dark

This is also the default Firefox Dev Edition theme.

screenshot from 2017-08-09 15-40-29

### PR DESCRIPTION
**Pull request by aeris**
Fix #116

### CODE REVIEW

**Comment by maximbaz** [comment]
Thanks! The list indeed looks good now, but the text in the search bar is still lightgray - could you please fix it too?

**Comment by aeris** [comment]
Hum… I have no trouble with search input 
screenshot_20170930_162216
Could you send me a screenshot with the problem ?

**Comment by maximbaz** [comment]
image

It is weird that your search input has a black background, the two screenshots in #116 and on my laptop all have white background and light-gray text.

**Comment by aeris** [comment]
OK, I push 8999687 to fix input too

**Comment by maximbaz** [comment]
Thank you, looks amazing now 🙂

image

**Pull request merged**
